#!/bin/bash

# Gather and format the arguments.
if [[ $1 == 0 ]] ; then
   SAVE_RESULTS=""
else
   SAVE_RESULTS="--save-results"
fi
if [[ $2 == 0 ]] ; then
   CONE_LIMIT=""
else
   CONE_LIMIT="--cone-limit $2"
fi
TAP_MODE="${3}"
IN_DIR="${4}"
CONE_FILE="${5}"
OUT_DIR="${6}"
SUB_DIR="${7}"

shopt -s nullglob  # With no matches, don't enter loop
for resource_file in "${IN_DIR}/${SUB_DIR}"/*.py; do
   base_filename=`basename ${resource_file}`
   resource_name=${base_filename%.py}

   set -x  # print out commands
   servicemon --batch --result-dir "${OUT_DIR}" \
      ${SAVE_RESULTS} --tap-mode ${TAP_MODE} \
      query \
      "${IN_DIR}/${SUB_DIR}"/"$resource_name".py \
      "${OUT_DIR}"/"$resource_name"-'%Y-%m-%d-%H-%M'.csv \
      --cone-file "${CONE_FILE}" \
      ${CONE_LIMIT} \
      >> "${OUT_DIR}"/"$resource_name"-`date "+%Y-%m-%d-%H-%M"`_runlog.txt 2>&1
   set +x

done
